### ISSUE TITLE
Crash app android OS 7.0 when run with flutter version 1.17.1

### ISSUE THREAD

**Issue by NguyenKimHieu** [minhvn/momo.vn#1]
When I debug app in android device OS 7.0 with project flutter version 1.17.1. Can you check this problem. Thank.

**Comment by minhvn** [comment]
> When I debug app in android device OS 7.0 with project flutter version 1.17.1. Can you check this problem. Thank.

Can give me log when app crash?
Thank Hiếu.

**Comment by NguyenKimHieu** [comment]
Here
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=-1, data=Intent { (has extras) }} to activity {com.example.testmomo/com.example.testmomo.MainActivity}: java.lang.ClassCastException: byte[] cannot be cast to java.lang.String
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
E/AndroidRuntime( 8517): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8517): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime( 8517): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8517): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 8517): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime( 8517): Caused by: java.lang.ClassCastException: byte[] cannot be cast to java.lang.String
E/AndroidRuntime( 8517): 	at com.minh.momo_vn.MomoVnPluginDelegate._handleResult(MomoVnPluginDelegate.kt:72)
E/AndroidRuntime( 8517): 	at com.minh.momo_vn.MomoVnPluginDelegate.onActivityResult(MomoVnPluginDelegate.kt:38)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime( 8517): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
E/AndroidRuntime( 8517): 	at android.app.Activity.dispatchActivityResult(Activity.java:6932)
E/AndroidRuntime( 8517): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
E/AndroidRuntime( 8517): 	... 9 more

**Comment by minhvn** [comment]
@NguyenKimHieu 
Hiếu chạy được chưa? Minh dùng version mới nhất thấy vẫn thanh toán được.

**Comment by NguyenKimHieu** [comment]
@minhvn Mình chạy được rồi. mình có sửa lại thành SDK_INT >= 26 thì chạy ổn rồi (debug trên app momo test) . Nhưng sau đó mình revert lại chạy trên bản momo live thì ok. Có vẻ vấn đề ở đây là app momo test response vs android OS 7.0 trở xuống. Dù sao thì app cũng đã chạy ổn rồi. Cảm ơn nhé. Close issue này giúp mình nhé.
![image](https://user-images.githubusercontent.com/32195486/86365252-782b0d80-bca3-11ea-97ea-0553dba4e6d0.png)

**Comment by minhvn** [comment]
@NguyenKimHieu Okay Hiếu, cảm ơn đã feedback :)
