### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by baoenzo** [minhvn/momo.vn#10]
Lúc build app nó hiện lỗiType mismatch: inferred type is String? but Any was expected ở cái file MomoVnPluginDelegate.kt. Mình chỉ mới add vào pubspec.yaml thôi. Chưa viết 1 dòng code nào cả.

**Comment by baoenzo** [comment]
Đã tự fix :((

**Comment by dungngo4520** [comment]
Bạn ơi bạn fix lỗi này như nào thế :((
