### ISSUE TITLE
Lỗi khi build app trên flutter

### ISSUE THREAD

**Issue by baoenzo** [minhvn/momo.vn#11]
Mình bị lỗi này ở phiên bản 1.0.3 , nhưng lên 1.0.4 vẫn bị đó là không thể build app trên flutter. Mong bạn fix ở các phiên bản tiếp theo
Lỗi này nằm ở file MomoVnPluginDelegate.kt và cách sửa là chỉ cần thêm toString() là được.
![image](https://user-images.githubusercontent.com/44154735/116886698-97901f80-ac53-11eb-9a80-a3e57d8d13d2.png)

**Comment by minhvn** [comment]
Cảm ơn bạn, để Minh thêm vào.

**Comment by minhvn** [comment]
Đã thêm, cảm ơn bạn nhiều.
