### ISSUE TITLE
Lỗi không thanh toán được trên Android phiên bản 1.0.4

### ISSUE THREAD

**Issue by loidoan** [minhvn/momo.vn#14]
Anh xem giúp với cứ mở thanh toán MOMO trên android là không được? IOS thì ok ! Em có log trên Firebase Crash. A xem qua hình giúp e với nha!

<img width="1152" alt="Screen Shot 2021-05-15 at 13 56 19" src="https://user-images.githubusercontent.com/8318770/118351329-9630f200-b585-11eb-8d25-5d9be426ddc4.png">
<img width="1152" alt="Screen Shot 2021-05-15 at 13 56 28" src="https://user-images.githubusercontent.com/8318770/118351332-9c26d300-b585-11eb-82ef-4bb1b3524e29.png">

**Comment by minhvn** [comment]
Cảm ơn bạn, để Minh check thử.

**Comment by minhvn** [comment]
@loidoan lỗi này còn không Lợi ơi?

**Comment by loidoan** [comment]
Ok rồi á anh
