### ISSUE TITLE
Upgrade to sound null safety

### ISSUE THREAD

**Issue by vukhacbiet** [minhvn/momo.vn#15]
Hiện Flutter đã lên version 2.2, bắt buộc các package phải lên sound null safety, mình mong @minhvn sớm cập nhật package lên để mọi người đang sử dụng package này có thể dễ dàng upgrade flutter version kể từ bản 2.2.

Xin cảm ơn.

**Comment by minhvn** [comment]
@vukhacbiet cảm ơn bạn,cuối tuần này Minh upgrade lên xem sao.

**Comment by minhvn** [comment]
Update rồi nha.
