### ISSUE TITLE
PluginRegistry$Registrar

### ISSUE THREAD

**Issue by hoangviet522** [minhvn/momo.vn#16]
Hi A minh, e có bị lỗi này a có thể xem qua dùm e được không
![image](https://user-images.githubusercontent.com/42379818/120464406-15685780-c3c7-11eb-992f-fbe2a9cd42bd.png)

**Comment by minhvn** [comment]
Trên máy thật hả Việt?

**Comment by hoangviet522** [comment]
Đúng rồi a trên máy thật, e chỉnh sửa file đó e chạy lại thì nó genera lại như ban đầu và bị lỗi

**Comment by minhvn** [comment]
Anh mới build lại trên ios, thấy chạy ổn, em bị android mà em đang làm gì đó? thấy là lạ.

**Comment by hoangviet522** [comment]
E chạy dc rồi a. A có demo nào về thanh toán bằng qrcode của momo ko a?
