### ISSUE TITLE
Update bảng 2.0 thanh toan trên IOS bị lỗi

### ISSUE THREAD

**Issue by loidoan** [minhvn/momo.vn#18]
Mình thanh toán MOMO với môi trường Production , phiên bảng trc đó thì ok. Mà khi update len 2.0 thì đã lỗi thanh toán, Crash lúc bắt đầu mở app MOMO.
<img width="1128" alt="Screen Shot 2021-06-10 at 18 25 26" src="https://user-images.githubusercontent.com/8318770/121517430-8f2cc080-ca19-11eb-9a83-9f01c28a107c.png">
<img width="1128" alt="Screen Shot 2021-06-10 at 18 26 07" src="https://user-images.githubusercontent.com/8318770/121517448-93f17480-ca19-11eb-9675-df0dbd09586d.png">

**Comment by minhvn** [comment]
Khả năng app của Momo production với test có gì đó khác nhau.
Ah, bản update mới có thêm tham số partner code, bạn thêm vào thử được
không nhé.

**Comment by minhvn** [comment]
Được chưa @loidoan ơi?

**Comment by loidoan** [comment]
> Được chưa @loidoan ơi?

Chưa được luôn anh. E quay về phiên bản trc đó thì được

**Comment by minhvn** [comment]
@loidoan em thử pull code mới nhất về thử nha. Hỗ trợ anh cái nhé, hihi.

**Comment by loidoan** [comment]
Ok anh. Để e thử nào

**Comment by loidoan** [comment]
> @loidoan em thử pull code mới nhất về thử nha. Hỗ trợ anh cái nhé, hihi.

OK rồi á anh. A lên LIB lun nào

**Comment by minhvn** [comment]
@cảm ơn @loidoan :)
