### ISSUE TITLE
Update version 2.0.0, lỗi partner code

### ISSUE THREAD

**Issue by liangbsu** [minhvn/momo.vn#19]
Khi gửi request payment lên momo server lỗi "partnerCode": "not match", bản 1.0.4 thì bình thường

**Comment by minhvn** [comment]
Bạn coi cấu hình có thêm tham số partner code, copy từ trên dán xuống là
được nhé. Minh đang kiểm tra lại trên ios mới.
Cảm ơn bạn.

**Comment by liangbsu** [comment]
Dạ em có thêm tham số partner code rồi nha anh, em test trên ios 14.6 khi em không thêm tham số partner code thì app crash ngay lúc vô app momo.

**Comment by minhvn** [comment]
@liangbsu thêm Partner code vô hoạt động rồi phải không?
