### ISSUE TITLE
Làm sao để có thể mở được app momo test chứ không phải CHPlay

### ISSUE THREAD

**Issue by hoangduc11** [minhvn/momo.vn#30]
Chào Minh!
Cho mình hỏi khi chọn thanh toán bằng momo á thì cứ auto mở chplay nó install momo mà trên máy đã cài momo (test) thì làm sao để mình có thể mở được momo(test) vậy? (Code bằng flutter sài momo_vn version 2.0.1)
Mong được Minh hỗ trợ.

**Comment by minhvn** [comment]
Bạn đổi version trong code qua v1.0.7 giúp với nhé.

**Comment by minhvn** [comment]
@hoangduc11 bạn update bản mới thử nhé. Cảm ơn bạn

**Comment by hoangduc11** [comment]
Cảm ơn Minh! Mình update version mới về được rồi nha!
