### ISSUE TITLE
Can not get back extra information when payment successfull

### ISSUE THREAD

**Issue by thienhaole92** [minhvn/momo.vn#5]
Before open MoMo app for testing i added some thing in extra and then i pay with MoMo. The payment success but on success respone the extra is empty

**Comment by minhvn** [comment]
Hi Hao, can you upgrade SDK >= 26?
Other ticker : https://github.com/minhvn/momo.vn/issues/1

**Comment by thienhaole92** [comment]
> Hi Hao, can you upgrade SDK >= 26?
> Other ticker : #1

Hi Minh, How to upgrade it in flutter project
