### ISSUE TITLE
License  of lib

### ISSUE THREAD

**Issue by ttpho** [minhvn/momo.vn#6]
@minhvn Thank you for your lib 
I read the LICENSE file, it is not detailed. 
https://github.com/minhvn/momo.vn/blob/v1.0.1/LICENSE
I want to use it but I don't know the license detail. 
I think it is a license is Apache or MIT. 
Please help me add license detail.

🙇

**Comment by minhvn** [comment]
Thank @ttpho , I have added https://github.com/minhvn/momo.vn/blob/master/LICENSE.
if have any update, can help me create pull request 👍 
Thanks.
Minh.

**Comment by ttpho** [comment]
@minhvn Thank you for your support 🙇 . 
I will close this issue.
