### ISSUE TITLE
Uri_link handle fails because Momo override openURL method

### ISSUE THREAD

**Issue by vukhacbiet** [minhvn/momo.vn#7]
Hàm override openURL của MoMo làm cho package Uri_link không hoạt động được, bạn có cách nào fix giúp mình không? (trên iOS)

**Comment by vukhacbiet** [comment]
Mình đang dùng package này để handle uri: https://pub.dev/packages/uni_links

**Comment by minhvn** [comment]
Hi @vukhacbiet , cái này mình chưa dùng nên không biết luôn á, bạn thử search xem sao.

**Comment by vukhacbiet** [comment]
Mình tạm viết lại đoạn code như sau để handle song song.

```
override func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
    MoMoPayment.handleOpenUrl(url: url, sourceApp: sourceApplication!)
    UniLinksPlugin.sharedInstance().application(application, open: url);
    return true;
  }
  
  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    MoMoPayment.handleOpenUrl(url: url, sourceApp: "")
    UniLinksPlugin.sharedInstance().application(app, open: url, options: options);
    return true;
  }

```
Nhưng thiết nghĩa hàm handleOpenUrl nên trả về boolean để dễ xử lý.

**Comment by minhvn** [comment]
@vukhacbiet cảm ơn bạn, để Minh check lại coi sao.

**Comment by minhvn** [comment]
Đã return true or false :) cảm ơn @vukhacbiet ;
