### ISSUE TITLE
Open Momo APP Not payment

### ISSUE THREAD

**Issue by toanlieu** [minhvn/momo.vn#8]
Mình chạy và thanh toán qua MOMO truyền những thông số cần thiết. Nhưng tới màn hình thanh toán trên app MOMO test cứ xoay xoay hoài. Không biết là lỗi code hay do app test MOMO đang lỗi. Ad có test được ko ạ? E cảm ơn ạ

**Comment by minhvn** [comment]
Chào bạn, đã mở được app Test MoMo thì có thể do app lúc đó đang gặp vấn đề, thử lại giúp Minh xem thế nào nhé. Bật debug lên, xem có lỗi gì ra màn hình không.

**Comment by toanlieu** [comment]
Hi Minh,

Mình chạy app example của Minh thì nó bị tình trạng này. https://drive.google.com/file/d/1eW0Lrg_-qPU5Z--r_65VJiZNOWyYJnc3/view?usp=sharing Minh xem qua video xem giúp mình thử nha. Cảm ơn Minh

**Comment by minhvn** [comment]
Minh có coi qua, thì cái này đã mở qua app rồi.
- Kiểm tra lại thông tin cấu hình đã đúng chưa? phải nhập thông tin cấu
hình vào nhé, sample của Minh cấu hình tạm.
- Nếu bước trên còn lỗi thì mở VS xem nó có bắn lỗi gì ra không nghen.

Vào Th 2, 11 thg 1, 2021 vào lúc 14:47 toanlieu <notifications@github.com>
đã viết:

**Comment by toanlieu** [comment]
@minhvn  Mình làm được rồi nha. Cảm ơn Minh nha

**Comment by minhvn** [comment]
Okay bạn, tốt quá, có gì star nghen :D

Vào Th 2, 11 thg 1, 2021 vào lúc 17:37 toanlieu <notifications@github.com>
đã viết:

**Comment by baoenzo** [comment]
@toanlieu Làm sao fix vậy bạn ơi , mình vừa fix xong lỗi kia thì bị lỗi y chang bạn.
